maps/vs_revenant.res
maps/vs_revenant.txt
sprites/vs/jinx/jx0firesmall.spr
sprites/vs/jinx/m_orflare1.spr
sound/vs/jinx/borg_rain.wav
sound/vs/jinx/jxfirecamp.wav
sound/vs/jinx/jxthunder01.wav
sound/vs/jinx/jxthunder02.wav
sound/vs/jinx/mr_rain1.wav
models/vs/jinx/rev_woodgibs.mdl
models/vs/jinx/wik_gat.mdl
models/vs/jinx/wik_gmn.mdl
models/vs/jinx/wik_readme.txt
gfx/env/vs/dmcpup.tga
gfx/env/vs/dmcprt.tga
gfx/env/vs/dmcplf.tga
gfx/env/vs/dmcpft.tga
gfx/env/vs/dmcpdn.tga
gfx/env/vs/dmcpbk.tga
